# Generated by Django 5.2.3 on 2025-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-22 00:00:00'),
            preserve_default=False,
        ),
    ]
