# Generated by Django 5.2.3 on 2025-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='poster_image/'),
        ),
    ]
